[package]
name = "dither"
version = "0.1.0"
authors = ["Zeda Thomas <zedae.z80@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
#Use opt-level = 3
opt-level = 3

[dependencies]
image = "0.23.8"
